#!/bin/bash
torch.cuda.empty_cache()

os.environ["FLASH_ATTENTION_FORCE_DISABLED"] = "1"
os.environ["WANDB_MODE"] = "disabled"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

MODEL_OUTPUT = "output_model"
os.makedirs(MODEL_OUTPUT, exist_ok=True)

MODEL_NAME = "Qwen/Qwen2.5-VL-3B-Instruct"
DATA_PATH = "08NV/fine_tune/train"
IMAGE_FOLDER = "08NV/images"

!accelerate launch "08NV/src/train/train_sft.py" \
    --deepspeed '08NV/scripts/zero2_offload.json' \
    --use_liger False \
    --data_path "$DATA_PATH" \
    --model_id "$MODEL_NAME" \
    --image_folder "$IMAGE_FOLDER" \
    --page_number 4 \
    --remove_unused_columns False \
    --freeze_vision_tower False \
    --freeze_llm True \
    --freeze_merger False \
    --bf16 False \
    --fp16 True \
    --lora_enable True \
    --disable_flash_attn2 True \
    --output_dir "$MODEL_OUTPUT" \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --gradient_checkpointing True \
    --save_strategy "epoch" \
    --save_steps 10 \
    --save_total_limit 10 \
    --dataloader_num_workers 0 \
    --per_device_train_batch_size 1 \
    --fp16_full_eval False \
    --image_min_pixels 1372 \
    --image_max_pixels 1372 \
    --bits 4 \
    --quant_type nf4 \
    --optim adamw_torch_fused \
    --optim_target_modules "q_proj,v_proj,o_proj" \
    --lora_namespan_exclude "['embed_tokens,lm_head']" \
    --num_train_epochs 1 \
    --do_eval True \
    --eval_strategy 'epoch' \
    --eval_data_path "08NV/fine_tune/validation" \
    --inference_image_path "08NV/images/1/4.jpg"
